{
 "title": "Brain",
 "description": "Brain API metrics",
 "tags": [
  "java",
  "ctac"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Environment", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_classes_loaded, instance)"
    }
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": {
     "query": "label_values(hikaricp_connections{job=~\"$job\", instance=~\"$instance\"}, pool)"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used{job=~\"$job\", instance=~\"$instance\", area=\"heap\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "[$job] [$instance] Scheduled",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "[$job] [$instance] Fetcher last refresh",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - backend_fetcher_last_successful_refresh{job=~\"$job\", instance=~\"$instance\", fetcher_name!~\"systel_cache.*\"}",
     "legendFormat": "[{{job}}] {{fetcher_name}}"
    }
   ]
  },
  {
   "title": "[$job] [$instance] Systel cache last refresh",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - backend_fetcher_last_successful_refresh{job=~\"$job\", instance=~\"$instance\", fetcher_name=~\"systel_cache.*\"}",
     "legendFormat": "[{{job}}] {{fetcher_name}}"
    }
   ]
  },
  {
   "title": "[$job] [$instance] Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used{job=~\"$job\", instance=~\"$instance\", area=\"heap\"})",
     "legendFormat": "Used heap"
    },
    {
     "expr": "sum(jvm_memory_max{job=~\"$job\", instance=~\"$instance\", area=\"heap\"})",
     "legendFormat": "Max heap"
    },
    {
     "expr": "sum(jvm_memory_used{job=~\"$job\", instance=~\"$instance\", area=\"nonheap\"})",
     "legendFormat": "Used non-heap"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_files_open{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Open files"
    },
    {
     "expr": "rate(process_files_open{job=~\"$job\", instance=~\"$instance\"}[10m])",
     "legendFormat": "Rate of file opening"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time{job=~\"$job\", instance=~\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{job=~\"$job\", instance=~\"$instance\", level=~\"WARN|ERROR\"}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(logback_events{job=~\"$job\", instance=~\"$instance\", level=~\"warn|error\"}[5m])",
     "legendFormat": "{{level}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "[$job] [$instance] Brain API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Error Request Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_count{job=~\"$job\", instance=~\"$instance\", status!~\"2..\"}[1m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Success Request Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_count{job=~\"$job\", instance=~\"$instance\", status=~\"2..\"}[1m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_sum{job=~\"$job\", instance=~\"$instance\"}[1m]) / rate(http_server_requests_count{job=~\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "[$job] [$instance] HTTP Dependencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Success Request Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_client_request_duration_count{job=~\"$job\", instance=~\"$instance\", status=~\"2..\"}[1m])",
     "legendFormat": "{{method}} [{{status}}] - {{host}}{{path}}"
    }
   ]
  },
  {
   "title": "Error Request Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_client_request_duration_count{job=~\"$job\", instance=~\"$instance\", status!~\"2..\"}[1m])",
     "legendFormat": "{{method}} [{{status}}] - {{host}}{{path}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_client_request_duration_sum{job=~\"$job\", instance=~\"$instance\"}[1m]) / rate(http_client_request_duration_count{job=~\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{method}} [{{status}}] - {{host}}{{path}}"
    }
   ]
  },
  {
   "title": "[$job] [$instance] JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 55 },
   "repeat": "memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used{job=~\"$job\", instance=~\"$instance\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed{job=~\"$job\", instance=~\"$instance\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max{job=~\"$job\", instance=~\"$instance\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_daemon{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_sum{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_count{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "[$job] [$instance] HikariCP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections{job=~\"$job\", instance=~\"$instance\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{job=~\"$job\", instance=~\"$instance\", pool=\"$hikaricp\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "hikaricp_connections_idle{job=~\"$job\", instance=~\"$instance\", pool=\"$hikaricp\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "hikaricp_connections_pending{job=~\"$job\", instance=~\"$instance\", pool=\"$hikaricp\"}",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Connection Timeout Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hikaricp_connections_timeout_total{job=~\"$job\", instance=~\"$instance\", pool=\"$hikaricp\"}"
    }
   ]
  },
  {
   "title": "Connection Creation Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_creation_sum{job=~\"$job\", instance=~\"$instance\", pool=\"$hikaricp\"} / hikaricp_connections_creation_count{job=~\"$job\", instance=~\"$instance\", pool=\"$hikaricp\"}",
     "legendFormat": "Creation Time"
    }
   ]
  },
  {
   "title": "Connection Usage Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_usage_sum{job=~\"$job\", instance=~\"$instance\", pool=\"$hikaricp\"} / hikaricp_connections_usage_count{job=~\"$job\", instance=~\"$instance\", pool=\"$hikaricp\"}",
     "legendFormat": "Usage Time"
    }
   ]
  },
  {
   "title": "Connection Acquire Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hikaricp_connections_acquire_sum{job=~\"$job\", instance=~\"$instance\", pool=\"$hikaricp\"} / hikaricp_connections_acquire_count{job=~\"$job\", instance=~\"$instance\", pool=\"$hikaricp\"}",
     "legendFormat": "Acquire Time"
    }
   ]
  }
 ]
}