package fr.sdis64.resources.indicators

import fr.sdis64.resources.UsualCtacSvg
import nl.adaptivity.xmlutil.serialization.XML
import java.nio.file.Path
import kotlin.io.path.nameWithoutExtension
import kotlin.io.path.readText
import kotlin.io.path.writeText

fun Path.writeVigipirateIconsComposableFunction(fromSvgs: List<Path>) {
    val functions = fromSvgs.sorted().map { file ->
        val svg = XML.decodeFromString(UsualCtacSvg.serializer(), file.readText())
        svg.toComposeFunction("Vigipirate${file.nameWithoutExtension.replaceFirstChar { it.uppercase() }}", "internal")
    }
    writeText(
        """
            /**
             * THIS FILE IS AUTOGENERATED BY `./gradlew :resources:generateUiResourcesComposableSourceFiles`, DO NOT EDIT MANUALLY
             */
            package fr.sdis64.ui.indicators
            
            import androidx.compose.runtime.Composable
            import org.jetbrains.compose.web.ExperimentalComposeWebSvgApi
            import org.jetbrains.compose.web.svg.*
            
${functions.joinToString("\n\n").prependIndent("            ")}
        """.trimIndent()
    )
}
