{
 "title": "Brain",
 "description": "Brain API metrics",
 "tags": [
  "java",
  "ctac"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "brain" },
   {
    "name": "cluster_environment",
    "label": "Environment",
    "query": {
     "query": "label_values(cluster_environment)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes, instance)"
    }
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}, pool)"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{job=~\"$job\", cluster_environment=~\"$cluster_environment\", area=\"heap\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "[$cluster_environment] Scheduled",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "[$cluster_environment] Fetcher last refresh",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - brain_fetcher_last_successful_refresh{job=\"brain\", cluster_environment=\"$cluster_environment\", fetcher_name!~\"systel_cache.*\"}",
     "legendFormat": "[{{cluster_environment}}] {{fetcher_name}}"
    }
   ]
  },
  {
   "title": "[$cluster_environment] Systel cache last refresh",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - brain_fetcher_last_successful_refresh{job=\"brain\", cluster_environment=\"$cluster_environment\", fetcher_name=~\"systel_cache.*\"}",
     "legendFormat": "[{{cluster_environment}}] {{fetcher_name}}"
    }
   ]
  },
  {
   "title": "[$cluster_environment] Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=~\"$job\", cluster_environment=~\"$cluster_environment\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$job\", cluster_environment=~\"$cluster_environment\", instance=~\"$instance\", area=\"heap\"})",
     "legendFormat": "Used heap"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=~\"$job\", cluster_environment=~\"$cluster_environment\", instance=~\"$instance\", area=\"heap\"})",
     "legendFormat": "Max heap"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$job\", cluster_environment=~\"$cluster_environment\", instance=~\"$instance\", area=\"nonheap\"})",
     "legendFormat": "Used non-heap"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_files_open_files{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}",
     "legendFormat": "Open files"
    },
    {
     "expr": "rate(process_files_open_files{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}[10m])",
     "legendFormat": "Rate of file opening"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=~\"$job\", cluster_environment=~\"$cluster_environment\", instance=~\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{application=\"brain\", cluster_environment=~\"$cluster_environment\", level=~\"WARN|ERROR\"}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(logback_events_total{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", level=~\"warn|error\"}[5m])",
     "legendFormat": "{{level}}",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "[$cluster_environment] Brain API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Error Request Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", status!~\"2..\"}[1m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Success Request Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", status=~\"2..\"}[1m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}[1m]) / rate(http_server_requests_seconds_count{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}[1m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "[$cluster_environment] HTTP Dependencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Success Request Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_client_request_duration_seconds_count{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", status=~\"2..\"}[1m])",
     "legendFormat": "{{method}} [{{status}}] - {{host}}{{path}}"
    }
   ]
  },
  {
   "title": "Error Request Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(http_client_request_duration_seconds_count{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", status!~\"2..\"}[1m])",
     "legendFormat": "{{method}} [{{status}}] - {{host}}{{path}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_client_request_duration_seconds_sum{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}[1m]) / rate(http_client_request_duration_seconds_count{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}[1m])",
     "legendFormat": "{{method}} [{{status}}] - {{host}}{{path}}"
    }
   ]
  },
  {
   "title": "[$cluster_environment] JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 55 },
   "repeat": "memory_pool_heap",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live_threads{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak_threads{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "[$cluster_environment] HikariCP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connections Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", pool=\"$hikaricp\"}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", pool=\"$hikaricp\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "hikaricp_connections_idle{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", pool=\"$hikaricp\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "hikaricp_connections_pending{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", pool=\"$hikaricp\"}",
       "legendFormat": "Pending"
      }
     ]
    },
    {
     "title": "Connection Timeout Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections_timeout_total{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", pool=\"$hikaricp\"}"
      }
     ]
    },
    {
     "title": "Connection Creation Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "hikaricp_connections_creation_seconds_sum{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", pool=\"$hikaricp\"} / hikaricp_connections_creation_seconds_count{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", pool=\"$hikaricp\"}",
       "legendFormat": "Creation Time"
      }
     ]
    },
    {
     "title": "Connection Usage Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "hikaricp_connections_usage_seconds_sum{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", pool=\"$hikaricp\"} / hikaricp_connections_usage_seconds_count{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", pool=\"$hikaricp\"}",
       "legendFormat": "Usage Time"
      }
     ]
    },
    {
     "title": "Connection Acquire Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "hikaricp_connections_acquire_seconds_sum{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", pool=\"$hikaricp\"} / hikaricp_connections_acquire_seconds_count{instance=~\"$instance\", job=~\"$job\", cluster_environment=~\"$cluster_environment\", pool=\"$hikaricp\"}",
       "legendFormat": "Acquire Time"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki4j",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time to perform operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki4j_send_time_seconds_sum{job=~\"$job\", instance=~\"$instance\", cluster_environment=~\"$cluster_environment\"}[5m]) / rate(loki4j_send_time_seconds_count{job=~\"$job\", instance=~\"$instance\", cluster_environment=~\"$cluster_environment\"}[5m])",
     "legendFormat": "HTTP send"
    },
    {
     "expr": "rate(loki4j_encode_time_seconds_sum{job=~\"$job\", instance=~\"$instance\", cluster_environment=~\"$cluster_environment\"}[5m]) / rate(loki4j_encode_time_seconds_count{job=~\"$job\", instance=~\"$instance\", cluster_environment=~\"$cluster_environment\"}[5m])",
     "legendFormat": "encode"
    },
    {
     "expr": "rate(loki4j_append_time_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[5m]) / rate(loki4j_append_time_seconds_count{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "single event append"
    }
   ]
  },
  {
   "title": "Number of batches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki4j_encode_batches_total{job=~\"$job\", instance=~\"$instance\", cluster_environment=~\"$cluster_environment\"}[5m])",
     "legendFormat": "processed by encoder"
    },
    {
     "expr": "rate(loki4j_send_batches_total{job=~\"$job\", instance=~\"$instance\", cluster_environment=~\"$cluster_environment\"}[5m])",
     "legendFormat": "sent to Loki"
    }
   ]
  },
  {
   "title": "Size of batches sent to Loki",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(loki4j_send_bytes_sum{job=~\"$job\", instance=~\"$instance\", cluster_environment=~\"$cluster_environment\"}[5m]) / rate(loki4j_send_bytes_count{job=~\"$job\", instance=~\"$instance\", cluster_environment=~\"$cluster_environment\"}[5m])",
     "legendFormat": "sent"
    }
   ]
  }
 ]
}