version: '3.8'

networks:
  ctac:
    name: ctac

volumes:
  prometheus_data:

services:
  prometheus:
    image: registry.hub.docker.com/archangelx360/ctac:prometheus-production
    deploy:
      update_config:
        order: stop-first
        failure_action: rollback
    ports:
      - "9090:9090"
    networks:
      - ctac
    volumes:
      - type: volume
        source: prometheus_data
        target: /prometheus
